[functions]
  directory = "apps/functions"
  included_files = ["apps/functions/.env"]
[build]
  base = "apps/gatsby"
  command = "pnpm run build"
[dev]
  #framework = "gatsby"
  base = "apps/gatsby"
  command = "pnpm run develop:gatsby"
  functionsPort = 7000
