name: Lint
"on":
  pull_request:
  push:
    branches:
      - main
      - staging
      - production
jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install asdf & tools
        uses: asdf-vm/actions/install@v2
      - name: asdf cache
        id: asdf-cache
        uses: actions/cache@v2
        with:
          path: ~/.asdf/
          key: ${{ runner.os }}-${{ hashFiles('**/.tool-versions') }}
      - name: Install dependencies
        run: yarn install
      - name: lint
        run: yarn run lint
